# Generated by Django 4.2.27 on 2026-02-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_attributes_category_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: iPhone 17 Pro Max', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Например: Премиальная техника. Под заказ. С гарантией.', max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание продукта', verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архивировано')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_blocks/', verbose_name='Изображение')),
                ('background_color', models.CharField(default='from-gray-900 via-gray-800 to-gray-900', help_text='Tailwind CSS классы для градиента', max_length=50, verbose_name='Фоновый цвет')),
                ('text_color', models.CharField(default='text-white', help_text='Tailwind CSS классы для текста', max_length=50, verbose_name='Цвет текста')),
                ('button_text', models.CharField(default='Заказать сейчас', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, help_text='URL или путь для кнопки', max_length=500, verbose_name='Ссылка кнопки')),
                ('product', models.ForeignKey(blank=True, help_text='Связанный продукт из каталога', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_blocks', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Герой-блок',
                'verbose_name_plural': 'Герой-блоки',
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
