# Generated by Django 6.0.2 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_heroblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroblock',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_blocks/', verbose_name='Фоновое изображение'),
        ),
    ]
