# Generated by Django 6.0.2 on 2026-02-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_heroblock_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_header_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать в верхнем меню'),
        ),
    ]
