# Generated by Django 6.0.2 on 2026-02-27 05:07

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroblock',
            name='video_mp4',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате .mp4 для фонового воспроизведения', null=True, upload_to='hero_blocks/videos/', validators=[apps.products.models.validate_video_file], verbose_name='Видео (MP4)'),
        ),
    ]
