# Generated by Django 6.0.2 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_heroblock_video_mp4'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='applies_to',
            field=models.CharField(
                choices=[('product', 'Товар'), ('variant', 'Вариант')],
                default='product',
                max_length=20,
                verbose_name='Применяется к',
            ),
        ),
        migrations.AddField(
            model_name='attribute',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязательный'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики товара'),
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={
                'ordering': ['sort_order', 'name'],
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
    ]
